name: Bishwa's Daily Commit

on:
  schedule:
    - cron: '*/1 * * * *' # Run every minute

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Random Text and Commit
      run: |
        FILE="random_text.md"

        if [ ! -f "$FILE" ]; then
          echo "Hello, my name is bishwa shah" > "$FILE"
          echo "Count: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'Count: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi

          NEXT_COUNT=$((CURRENT_COUNT + 1))

          sed -i "/Count: /c\Count: $NEXT_COUNT" "$FILE"
        fi

        git config --global user.name "beesou777"
        git config --global user.email "sbeesou@gmail.com"
        git add "$FILE"
        git commit -m "Hello, my name is bishwa shah nice to meet you"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
